In [9]:
import numpy as np
import math

In [2]:
#Question 1
a=np.random.rand(10,1)
print(a)
a.mean()

[[0.22509431]
 [0.39809604]
 [0.19386636]
 [0.84157784]
 [0.4783799 ]
 [0.72992174]
 [0.78834774]
 [0.58791702]
 [0.89772247]
 [0.29549927]]


0.5436422700519115

In [4]:
#Question 2
b=np.random.rand(20,1)
print(b)
b.var()

[[0.9285354 ]
 [0.82416802]
 [0.471324  ]
 [0.11966799]
 [0.48224276]
 [0.41550894]
 [0.87311429]
 [0.60617687]
 [0.86220404]
 [0.76336254]
 [0.16208698]
 [0.41528135]
 [0.55824439]
 [0.45203691]
 [0.87181055]
 [0.3752686 ]
 [0.14905812]
 [0.4884476 ]
 [0.91474215]
 [0.27392912]]


0.06846205589801509

In [5]:
#Question 3
A=np.random.rand(10,20)
print(A)
B=np.random.rand(20,25)
print(B)
C=np.dot(A,B)
print(C)

[[0.52788262 0.97519405 0.72718495 0.36294583 0.04004139 0.79549094
  0.30432706 0.36543756 0.58069232 0.08193367 0.40788642 0.88763731
  0.38227158 0.96511656 0.96353114 0.6335758  0.68865938 0.32221515
  0.80989879 0.77150653]
 [0.3473082  0.79829719 0.1321364  0.50858593 0.21289814 0.61262651
  0.50058756 0.23343455 0.53859464 0.11869111 0.0567705  0.51560023
  0.33076682 0.20839308 0.03870186 0.88435707 0.95308248 0.8665691
  0.98938325 0.61245355]
 [0.98244055 0.7059709  0.78680714 0.76127197 0.42925898 0.52136746
  0.01137268 0.80177823 0.81867359 0.00176598 0.61816916 0.89752766
  0.18727709 0.36857309 0.77129947 0.10663046 0.26284177 0.45471256
  0.79713223 0.27863535]
 [0.80943551 0.17115097 0.4299124  0.88505654 0.2984988  0.44529632
  0.04488781 0.4010565  0.96512962 0.79190883 0.29623739 0.11516057
  0.74154951 0.80511962 0.79517548 0.92989232 0.79671883 0.0807576
  0.42414696 0.89036455]
 [0.67166757 0.87450458 0.9662293  0.35686409 0.36193506 0.8961791
  0.45255924 0.3422

In [10]:
#Question 4
b=np.arange(10).reshape(10,1)
print(b)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [11]:
def f(x):
    return 1 / (1 + math.exp(-x))
np.apply_along_axis(f,1,b)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])